### PR TITLE
fix: don't hard-error on unreadable messages

### LINKED ISSUE #87: Disable colored logs when no tty
Galileo always emits colored logs, which breaks log-level detection when aggregating events and searching across them. As we've done in e.g. `pd`, let's conditionally disable colorization of log messages when no tty exists. That way, devs can still see colored events, but log slurpers will not have their ingestion polluted with escape codes.

### LINKED ISSUE #101: galileo errors hard if it can't read a message
Saw a new error today, under heavy load:

```
galileo thread 'tokio-runtime-worker' panicked at src/handler.rs:264:61:
galileo called `Result::unwrap()` on an `Err` value:
galileo     member: None,
galileo }
galileo note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

That points to trying to create a MessageInfo object: https://github.com/penumbra-zone/galileo/blob/ec84f805898ba343448f30f0118a6dfa2662dc4a/src/handler.rs#L264 which fails for some reason. We can't return an error there, but we can at least log the error and return, rather than unexploding via unwrap.

### PR DESCRIPTION
**Pull request by conorsch**
For reasons I don't understand, Galileo can fail to create a MessageInfo object from a Message. If that conversion fails, we can't proceed. The  unwrap was causing a fatal error; instead, let's just log it and keep going. Closes #101.

While I was in there, also patched up the logging, to make the logs easier to read when searching. Therefore closes #87.

### CODE REVIEW

File: src/tracing.rs [hunk 1]
```diff
@@ -1,8 +1,12 @@
+use std::io::IsTerminal as _;
 use tracing_subscriber::{prelude::*, EnvFilter};
 
 /// Initializes a tracing subscriber.
 pub(crate) fn init_subscriber() -> anyhow::Result<()> {
-    let fmt_layer = tracing_subscriber::fmt::layer().with_target(true);
+    let fmt_layer = tracing_subscriber::fmt::layer()
+        .with_target(true)
+        .with_ansi(std::io::stderr().is_terminal())
```
Comment (cratelyn) [inline src/tracing.rs:8]: logging to stderr feels _mildly_ surprising to me, but i don't have a strong opinion about this 👍

File: src/handler.rs [hunk 2]
```diff
@@ -261,7 +261,15 @@ impl EventHandler for Handler {
     /// window, then Galileo will respond instructing the user to wait longer.
     async fn message(&self, ctx: Context, message: Message) {
         // Check whether we should proceed.
-        let message_info = MessageInfo::new(&message, &ctx).unwrap();
+        let message_info = match MessageInfo::new(&message, &ctx) {
+            Ok(m) => m,
+            Err(e) => {
+                // We can't return an error, but we also can't proceed, so log the error
+                // and bare-return to bail out.
```
Comment (cratelyn) [inline src/handler.rs:268]:
```suggestion
                // and early-return to bail out.
```

lightly held comment nit, tioli ("take-it-or-leave-it")

File: src/handler.rs [hunk 3]
```diff
@@ -261,7 +261,15 @@ impl EventHandler for Handler {
     /// window, then Galileo will respond instructing the user to wait longer.
     async fn message(&self, ctx: Context, message: Message) {
         // Check whether we should proceed.
-        let message_info = MessageInfo::new(&message, &ctx).unwrap();
+        let message_info = match MessageInfo::new(&message, &ctx) {
```
Comment (cratelyn) [inline src/handler.rs:264]: this looks great 👍

eventually it could be cool to expose a metric counting messages observed / parsed, but that's another item for the rainy day bucket 🙂

**Review by cratelyn — COMMENTED** [review]
✅ in spirit, 💬 in process since this is a draft. nice, simple fix!

File: src/tracing.rs (hunk 1 above)
Comment (conorsch) [reply src/tracing.rs:8]: Yeah, subjective, I guess. Putting on my sysadmin hat, I feel strongly that "stdout is for output, stderr is for logging and diagnostics." But in the case of `galileo serve`, where the _only_ output is logging, stdout is probably fine. Old habits die hard.
